fix: Add `install` target to makefile to facilitate setup

diff --git a/template/{{.package_name}}/Makefile.tmpl b/template/{{.package_name}}/Makefile.tmpl
--- a/template/{{.package_name}}/Makefile.tmpl
+++ b/template/{{.package_name}}/Makefile.tmpl
@@ -1,16 +1,53 @@
-# ANSI escape codes
-GREEN=\033[0;32m
-RESET=\033[0m
+.PHONY: install setup clean test deploy_dev deploy_acc deploy_prd destroy_dev destroy_acc destroy_prd repo module module_azure module_dlt module_gitlab module_vscode
+
+install:
+	@which brew > /dev/null || (echo "Homebrew is not installed. Installing Homebrew..." && /bin/bash -c "$$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)")
+
+	@echo "Installing required tools..."
+
+	@if ! command -v databricks >/dev/null 2>&1; then \
+		echo "Tapping databricks..."; \
+		brew tap databricks/tap; \
+		brew install databricks; \
+	else \
+		echo "Databricks is already installed. Skipping."; \
+	fi
+
+	@for tool in git poetry pyenv gh; do \
+		if ! command -v $$tool >/dev/null 2>&1; then \
+			echo "Installing $$tool..."; \
+			brew install $$tool; \
+		else \
+			echo "$$tool is already installed. Skipping."; \
+		fi; \
+	done
+
+	@echo "Adding pyenv configuration to .zprofile (environment variables for login shells)"
+	@grep -q '# pyenv' ~/.zshrc || (printf '\n# pyenv configuration (added by `revo-asset-bundle-templates` on %s)\n' "$$(date +"%Y-%m-%d %H:%M:%S")" >> ~/.zshrc)
+	@grep -q 'PYENV_ROOT' ~/.zshrc || (echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> ~/.zshrc)
+	@grep -q 'PYENV_ROOT/bin' ~/.zshrc || (echo '[[ -d $$PYENV_ROOT/bin ]] && export PATH="$$PYENV_ROOT/bin:$$PATH"' >> ~/.zshrc)
+	@grep -q 'pyenv init' ~/.zshrc || (echo 'eval "$$(pyenv init -)"' >> ~/.zshrc)
+
+	@echo "Adding pyenv configuration to .zshrc    (environment variables for interactive shells)"
+	@grep -q '# pyenv' ~/.zprofile || (printf '\n# pyenv configuration (added by `revo-asset-bundle-templates` on %s)\n' "$$(date +"%Y-%m-%d %H:%M:%S")" >> ~/.zprofile)
+	@grep -q 'PYENV_ROOT' ~/.zprofile || (echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> ~/.zprofile)
+	@grep -q 'PYENV_ROOT/bin' ~/.zprofile || (echo '[[ -d $$PYENV_ROOT/bin ]] && export PATH="$$PYENV_ROOT/bin:$$PATH"' >> ~/.zprofile)
+	@grep -q 'pyenv init' ~/.zprofile || (echo 'eval "$$(pyenv init -)"' >> ~/.zprofile)
+
+	@echo "All tools installed successfully."
 
 setup:
 	@echo "Please ensure you have the following tools installed and configured:"
-	@echo "  - python"
 	@echo "  - pyenv"
+	@echo "  - git"
+	@echo "  - gh (GitHub CLI)"
 	@echo "  - poetry >= 1.6.1"
 	@echo ""
 
-	@command -v python >/dev/null 2>&1 || { echo >&2 "Python is not installed. Exiting."; exit 1; }
-	@command -v pyenv >/dev/null 2>&1 || { echo >&2 "pyenv is not installed. Exiting."; exit 1; }
+	@for tool in pyenv git gh; do \
+		@command -v $$tool >/dev/null 2>&1 || { echo >&2 "$$tool is not installed. Exiting."; exit 1; }
+	done
+
 	@if ! command -v poetry >/dev/null 2>&1; then \
 		echo >&2 "Poetry is not installed. Exiting."; exit 1; \
 	else \
@@ -19,18 +56,6 @@ setup:
 		if [ "$$(echo -e "$$POETRY_VERSION\n$$REQUIRED_VERSION" | sort -V | head -n1)" != "$$REQUIRED_VERSION" ]; then \
 			echo >&2 "Poetry version $$POETRY_VERSION is less than required version $$REQUIRED_VERSION. Please upgrade it."; exit 1; \
 		fi \
-	fi
-	@if ! command -v python >/dev/null 2>&1; then \
-		echo "Python is not configured correctly."; \
-		echo "Make sure to add the following lines to the .zshrc / .bashrc configuration file in your home directory:"; \
-		echo ""; \
-		echo "# pyenv"; \
-		echo 'export PATH="$$HOME/.pyenv/bin:$$PATH"'; \
-		echo 'eval "$$(pyenv init --path)"'; \
-		echo 'eval "$$(pyenv init -)"'; \
-		echo ""; \
-		echo "Exiting"; \
-		exit 1; \
 	fi
 
 	@PYTHON_VERSION=$$(cat .python-version); \
@@ -70,55 +95,47 @@ test:
 	poetry install --only-root
 	pytest tests --cov=src  --cov-report html --cov-report term
 
-deploy_dev:
+deploy_%:
+	@if [ "$*" != "dev" ] && [ "$*" != "acc" ] && [ "$*" != "prd" ]; then \
+		echo "Error: Invalid environment. Use 'dev', 'acc', or 'prd'."; \
+		exit 1; \
+	fi
 	.venv/bin/pre-commit run --all-files
 	poetry update
 	poetry build
-
 	@PROFILE_NAME="{{.profile_name}}"; \
 	output=$$(databricks auth env --profile "$$PROFILE_NAME" 2>&1); \
 	if [[ $$output == *"Error: resolve:"* ]]; then \
 		databricks configure --profile "$$PROFILE_NAME"; \
 	else \
-		databricks bundle deploy --profile "$$PROFILE_NAME"; \
+		databricks bundle deploy --profile "$$PROFILE_NAME" $$(if [ "$*" != "dev" ]; then echo "--target $*"; fi); \
 	fi
 
-destroy_dev:
-	@PROFILE_NAME="{{.profile_name}}"; \
-	output=$$(databricks auth env --profile "$$PROFILE_NAME" 2>&1); \
-	if [[ $$output == *"Error: resolve:"* ]]; then \
-		databricks configure --profile "$$PROFILE_NAME"; \
-	else \
-		databricks bundle destroy --profile "$$PROFILE_NAME"; \
+destroy_%:
+	@if [ "$*" != "dev" ] && [ "$*" != "acc" ] && [ "$*" != "prd" ]; then \
+		echo "Error: Invalid environment. Use 'dev', 'acc', or 'prd'."; \
+		exit 1; \
 	fi
-
-deploy_prod:
-	.venv/bin/pre-commit run --all-files
-	poetry update
-	poetry build
-
 	@PROFILE_NAME="{{.profile_name}}"; \
 	output=$$(databricks auth env --profile "$$PROFILE_NAME" 2>&1); \
 	if [[ $$output == *"Error: resolve:"* ]]; then \
 		databricks configure --profile "$$PROFILE_NAME"; \
 	else \
-		databricks bundle deploy --profile "$$PROFILE_NAME" --target prod; \
-	fi
-
-destroy_prod:
-	@PROFILE_NAME="{{.profile_name}}"; \
-	output=$$(databricks auth env --profile "$$PROFILE_NAME" 2>&1); \
-	if [[ $$output == *"Error: resolve:"* ]]; then \
-		databricks configure --profile "$$PROFILE_NAME"; \
-	else \
-		databricks bundle destroy --profile "$$PROFILE_NAME" --target prod; \
+		databricks bundle destroy --profile "$$PROFILE_NAME" --target $*; \
 	fi
 
 # Create a repository in RevoData's GitHub, and adds a remote to the local git repo
 repo:
+	# ANSI escape codes
+	GREEN=\033[0;32m
+	RESET=\033[0m
 	@printf "$(GREEN)Creating repository in RevoData's GitHub...$(RESET)\n"
 	@PROJECT_NAME=$$(grep 'name =' pyproject.toml | awk -F'"' '{print $$2}'); \
 	REPO_DESCRIPTION=$$(grep 'description =' pyproject.toml | awk -F'"' '{print $$2}'); \
+	if ! gh auth status >/dev/null 2>&1; then \
+		echo "Error: GitHub CLI is not authenticated. Please run 'gh auth login' first."; \
+		exit 1; \
+	fi; \
 	if ! gh repo view revodatanl/$$PROJECT_NAME > /dev/null 2>&1; then \
 		gh repo create revodatanl/$$PROJECT_NAME -y --private -d "$$REPO_DESCRIPTION" > /dev/null 2>&1; \
 		(git remote | grep origin || git remote add origin git@github.com:revodatanl/$$PROJECT_NAME.git) > /dev/null 2>&1; \
@@ -135,7 +152,7 @@ module:
 	@echo "1) DLT"
 	@echo "2) Azure DevOps"
 	@echo "3) GitLab"
-	@echo "4) VSCode settings"
+	@echo "4) VSCode settings (update)"
 	@read -p "Enter the number of the module you want to deploy: " choice; \
 	case $$choice in \
 		1) $(MAKE) module_dlt;; \
