✨ feat(modules): integrate deploy-dab pipeline by default in template, effectively making revodata modules redundant
- Integrated Azure DevOps and GitHub workflows for deploying Databricks Asset Bundles.
- Removed outdated deployment templates and JSON schema files from modules.

diff --git a/modules/Makefile b/modules/Makefile
--- a/modules/Makefile
+++ b/modules/Makefile
@@ -2,25 +2,6 @@
 
 .DEFAULT_GOAL := module
 
-# Create a repository in RevoData's GitHub, and adds a remote to the local git repo
-repo:
-	@printf "Creating repository in RevoData's GitHub...\n"
-	@PROJECT_NAME=$$(grep 'name =' pyproject.toml | awk -F'"' '{print $$2}')
-	@REPO_DESCRIPTION=$$(grep 'description =' pyproject.toml | awk -F'"' '{print $$2}')
-	@if ! gh auth status >/dev/null 2>&1; then \
-		echo "Error: GitHub CLI is not authenticated. Please run 'gh auth login' first."; \
-		exit 1; \
-	fi
-	@if ! gh repo view revodatanl/$$PROJECT_NAME > /dev/null 2>&1; then \
-		gh repo create revodatanl/$$PROJECT_NAME -y --private -d "$$REPO_DESCRIPTION" > /dev/null 2>&1; \
-		(git remote | grep origin || git remote add origin git@github.com:revodatanl/$$PROJECT_NAME.git) > /dev/null 2>&1; \
-		printf "Repository created at revodatanl/$$PROJECT_NAME...\n"; \
-		printf "Publishing project...\n"; \
-		printf "Repository published.\n"; \
-	else \
-		printf "Repository revodatanl/$$PROJECT_NAME already exists.\n"; \
-	fi
-
 # Add custom RevoData modules to the project
 module:
 	@echo "Select the module to deploy:"
@@ -47,3 +28,24 @@ module_%:
 			echo "Exiting." >&2; \
 		fi; \
 	}
+
+# Create a repository in RevoData's GitHub, and adds a remote to the local git repo
+repo:
+	@printf "Creating repository in RevoData's GitHub...\n"
+	@PROJECT_NAME=$$(grep 'name =' pyproject.toml | awk -F'"' '{print $$2}')
+	@REPO_DESCRIPTION=$$(grep 'description =' pyproject.toml | awk -F'"' '{print $$2}')
+	@if ! gh auth status >/dev/null 2>&1; then \
+		echo "Error: GitHub CLI is not authenticated. Please run 'gh auth login' first."; \
+		exit 1; \
+	fi
+	@if ! gh repo view revodatanl/$$PROJECT_NAME > /dev/null 2>&1; then \
+		gh repo create revodatanl/$$PROJECT_NAME -y --private -d "$$REPO_DESCRIPTION" > /dev/null 2>&1; \
+		(git remote | grep origin || git remote add origin git@github.com:revodatanl/$$PROJECT_NAME.git) > /dev/null 2>&1; \
+		printf "Repository created at revodatanl/$$PROJECT_NAME...\n"; \
+		printf "Publishing project...\n"; \
+		printf "Repository published.\n"; \
+	else \
+		printf "Repository revodatanl/$$PROJECT_NAME already exists.\n"; \
+	fi
+
+# Create an pre-configured python-only project
