docs: update commands page

diff --git a/template/{{.project_name}}/Makefile.tmpl b/template/{{.project_name}}/Makefile.tmpl
--- a/template/{{.project_name}}/Makefile.tmpl
+++ b/template/{{.project_name}}/Makefile.tmpl
@@ -26,17 +26,25 @@ install:
 	pyenv install --skip-existing $$PYTHON_VERSION; \
 	pyenv local $$PYTHON_VERSION; \
 
-	@echo "Adding pyenv configuration to .zprofile (environment variables for login shells)"
-	@grep -q '# pyenv' ~/.zshrc || (printf '\n# pyenv configuration (added by `revo-asset-bundle-templates` on %s)\n' "$$(date +"%Y-%m-%d %H:%M:%S")" >> ~/.zshrc)
-	@grep -q 'PYENV_ROOT' ~/.zshrc || (echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> ~/.zshrc)
-	@grep -q 'PYENV_ROOT/bin' ~/.zshrc || (echo '[[ -d $$PYENV_ROOT/bin ]] && export PATH="$$PYENV_ROOT/bin:$$PATH"' >> ~/.zshrc)
-	@grep -q 'pyenv init' ~/.zshrc || (echo 'eval "$$(pyenv init -)"' >> ~/.zshrc)
+	@if ! grep -q '# pyenv configuration' ~/.zshrc; then \
+		echo "Adding pyenv configuration to .zshrc (for interactive shells)..."; \
+		printf '\n# pyenv configuration (added on %s)\n' "$$(date +"%Y-%m-%d %H:%M:%S")" >> ~/.zshrc; \
+		echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> ~/.zshrc; \
+		echo '[[ -d $$PYENV_ROOT/bin ]] && export PATH="$$PYENV_ROOT/bin:$$PATH"' >> ~/.zshrc; \
+		echo 'eval "$$(pyenv init -)"' >> ~/.zshrc; \
+	else \
+		echo "Pyenv configuration already exists in .zshrc. Skipping."; \
+	fi
 
-	@echo "Adding pyenv configuration to .zshrc    (environment variables for interactive shells)"
-	@grep -q '# pyenv' ~/.zprofile || (printf '\n# pyenv configuration (added by `revo-asset-bundle-templates` on %s)\n' "$$(date +"%Y-%m-%d %H:%M:%S")" >> ~/.zprofile)
-	@grep -q 'PYENV_ROOT' ~/.zprofile || (echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> ~/.zprofile)
-	@grep -q 'PYENV_ROOT/bin' ~/.zprofile || (echo '[[ -d $$PYENV_ROOT/bin ]] && export PATH="$$PYENV_ROOT/bin:$$PATH"' >> ~/.zprofile)
-	@grep -q 'pyenv init' ~/.zprofile || (echo 'eval "$$(pyenv init -)"' >> ~/.zprofile)
+	@if ! grep -q '# pyenv configuration' ~/.zprofile; then \
+		echo "Adding pyenv configuration to .zprofile (for login shells)..."; \
+		printf '\n# pyenv configuration (added on %s)\n' "$$(date +"%Y-%m-%d %H:%M:%S")" >> ~/.zprofile; \
+		echo 'export PYENV_ROOT="$$HOME/.pyenv"' >> ~/.zprofile; \
+		echo '[[ -d $$PYENV_ROOT/bin ]] && export PATH="$$PYENV_ROOT/bin:$$PATH"' >> ~/.zprofile; \
+		echo 'eval "$$(pyenv init --path)"' >> ~/.zprofile; \
+	else \
+		echo "Pyenv configuration already exists in .zprofile. Skipping."; \
+	fi
 
 	@echo "Restarting the terminal..."
 	@exec zsh -c "source ~/.zshrc"
@@ -93,8 +101,8 @@ deploy_%:
 	fi
 
 destroy_%:
-	@if [ "$*" != "dev" ] && [ "$*" != "acc" ] && [ "$*" != "prd" ]; then \
-		echo "Error: Invalid environment. Use 'dev', 'acc', or 'prd'."; \
+	@if [ "$*" != "dev" ] && [ "$*" != "prd" ]; then \
+		echo "Error: Invalid environment. Use 'dev'or 'prd'."; \
 		exit 1; \
 	fi
 	@PROFILE_NAME="{{.profile_name}}"; \
